cache: bundle
sudo: false
language: ruby
rvm:
  - 2.4.4
  - 2.5.1
  - ruby-head
env:
  - RAILS_VERSION="~> 5.2.0"
  - RAILS_VERSION="~> 5.1.0"
  - RAILS_VERSION="~> 5.0"
  - RAILS_VERSION="~> 4.2"
script: bundle exec rake ci
